[colors]
[colors.primary]
background = "#FFFCF0"
foreground = "#100F0F"
dim_foreground = "#585652"

[colors.cursor]
text = "#FFFCF0"
cursor = "#100F0F"

[colors.vi_mode_cursor]
text = "#FFFCF0"
cursor = "#100F0F"

[colors.selection]
text = "CellForeground"
background = "#B7B5AC"

[colors.normal]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#205EA6"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#E6E4D9"

[colors.bright]
black = "#403E3C"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

[colors.dim]
black = "#585652"
red = "#df8276"
green = "#abb770"
yellow = "#debd57"
blue = "#638dbc"
magenta = "#dd8db2"
cyan = "#75c2b7"
white = "#eeebe0"
